name: Ubuntu CI UT

on: [push, pull_request]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'run-ubuntu-ci')"
    steps:
    - uses: actions/checkout@v2
    - name: cache geode
      uses: actions/cache@v2
      id: cache-geode
      with:
        path: ~/apache-geode
        key: apache-geode
    - name: install geode
      env:
        CACHE_HIT: ${{steps.cache-geode.outputs.cache-hit}}
        GEODE_VERSION: 1.13.0
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          wget "https://www.apache.org/dyn/closer.cgi?action=download&filename=geode/${GEODE_VERSION}/apache-geode-${GEODE_VERSION}.tgz" --quiet -O - | tar xzf - && mv apache-geode-${GEODE_VERSION} ~/apache-geode
        fi
    - name: install doxygen
      run: sudo apt-get update && sudo apt-get install -yq doxygen
    - name: mkdir build
      run: mkdir build
    - name: cmake configure
      run: export GEODE_HOME=~/apache-geode && cmake -Bbuild
    - name: cmake build
      run: cmake --build build/ --target apache-geode_unittests -- -j2
    - name: unit tests
      run: build/cppcache/test/apache-geode_unittests
