name: Ubuntu CI Format

on: [push, pull_request]

jobs:
  clangformat-version6:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'run-ubuntu-ci')"
    steps:
    - uses: actions/checkout@v2
    - name: cache geode
      uses: actions/cache@v2
      id: cache-geode
      with:
        path: ~/apache-geode
        key: apache-geode
      env:
        GEODE_VERSION: 1.13.0
    - name: install geode
      env:
        CACHE_HIT: ${{steps.cache-geode.outputs.cache-hit}}
        GEODE_VERSION: 1.13.0
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          wget "https://www.apache.org/dyn/closer.cgi?action=download&filename=geode/${GEODE_VERSION}/apache-geode-${GEODE_VERSION}.tgz" --quiet -O - | tar xzf - && mv apache-geode-${GEODE_VERSION} ~/apache-geode
        fi
    - name: install doxygen
      run: sudo apt-get update && sudo apt-get install -yq doxygen
    - name: mkdir build
      run: mkdir build
    - name: use clang 6
      run: sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 999 && sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-6.0 999 && sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-6.0 999 && sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-6.0 999 && sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-6.0 999
    - name: cmake configure
      run: export GEODE_HOME=~/apache-geode && cmake -Bbuild
    - name: cmake all-clangformat
      run: cmake --build build/ --target all-clangformat && git diff --exit-code