name: Ubuntu CI RAT

on: [push, pull_request]

jobs:
  rat:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'run-ubuntu-ci')"
    steps:
    - uses: actions/checkout@v2
    - name: cache geode
      uses: actions/cache@v2
      id: cache-geode
      with:
        path: ~/apache-geode
        key: apache-geode
    - name: install geode
      env:
        CACHE_HIT: ${{steps.cache-geode.outputs.cache-hit}}
        GEODE_VERSION: 1.13.0
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          wget "https://www.apache.org/dyn/closer.cgi?action=download&filename=geode/${GEODE_VERSION}/apache-geode-${GEODE_VERSION}.tgz" --quiet -O - | tar xzf - && mv apache-geode-${GEODE_VERSION} ~/apache-geode
        fi
    - name: install rat
      run: wget "https://www.apache.org/dyn/closer.cgi?action=download&filename=creadur/apache-rat-${RAT_VERSION}/apache-rat-${RAT_VERSION}-bin.tar.gz" --quiet -O - | tar xzf - && mv apache-rat-${RAT_VERSION} ..
      env:
        RAT_VERSION: 0.13
    - name: install doxygen
      run: sudo apt-get update && sudo apt-get install -yq doxygen
    - name: mkdir build
      run: mkdir build
    - name: cmake configure
      run: export GEODE_HOME=~/apache-geode && export RAT_HOME=$GITHUB_WORKSPACE/../apache-rat-$RAT_VERSION && cmake -Bbuild -DUSE_RAT=ON
      env:
        RAT_VERSION: 0.13
    - name: cmake rat check
      run: cmake --build build/ --target rat-check